on:
  release:
      types: [released]

jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
    #PIC18F4550
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F4550
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: #https://gist.github.com/microside-mx/2b90284f3092bff0abda76b7713e8e4b
          gist_title: 23-DHT11-ccs-4550.c
          gist_description: Prácticas PIC CCS
          github_file: Proyecto/PIC18F4550/DHT11.c
          file_encoding: WINDOWS-1252
    #PIC18F45K50
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC18F45K50
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: #https://gist.github.com/microside-mx/ce08cbfc2ec19062fa8ab7289a3ad753
          gist_title: 23-DHT11-CCS.c
          gist_description: Prácticas PIC CCS
          github_file: Proyecto/PIC18F45K50/DHT11.c
          file_encoding: WINDOWS-1252
